dist: xenial
language: rust

rust:
  - nightly-2020-08-13
env:
  - RUSTFLAGS="-D warnings"

addons:
  apt:
    update: true

install:
  - rustup component add clippy
  - rustup component add rustfmt
  - rustup component add rust-src
  - cargo install cargo-xbuild
  - sudo apt-get install -y mtools
  - wget https://download.clearlinux.org/releases/28660/clear/clear-28660-kvm.img.xz
  - unxz clear-28660-kvm.img.xz
  - ./make-test-disks.sh

script:
  - cargo xbuild --release --target target.json
  - cargo xclippy --target target.json
  - cargo clippy --all-targets --all-features
  - cargo fmt --all -- --check
  - cargo test

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: target/target/release/hypervisor-fw
  skip_cleanup: true
  on:
    tags: true

