[toolchain]
channel = "nightly-2023-11-10"
components = ["rust-src", "clippy", "rustfmt"]
targets = [
    "aarch64-unknown-linux-gnu",
    "riscv64gc-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
]
profile = "default"
